[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
remappings = ["@openzeppelin/=node_modules/@openzeppelin/"]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[profile.solc]
version = "0.8.10"
evmVersion = "istanbul" # Specify the EVM version here